apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:LoQTMUGfxuJcQcLpG5BwtoF4SxXMRExd784xAjSKB2qTBiBmMALEit6y8AKORkxodZ8+iTDGfF3IJaJsyhPquLyedtMhRcUtHxyT810NP3hMUw/tb8xCkxCupM/oPNB66/sJOg3AycSSXR6C5V+hI7UB5o6iTr0ZU8UYVswN3zfwmXXR7ydkW1lELmwdKj1e/GILomOeWUIF+YOlOCMQIV+WKOD8ZJ/E+REDkeZt+CUL+EFFZxV39/npINGA9KFQbFllVSywpNFpPix6dDPZKPqk6myXO23neNDQtTtwY69xjJl9brNgXllkg1c=,iv:jfF3fKp5SlfF7sBYO6ww2k1nbhGgyTqsXGeL76ZvAos=,tag:dokgQOwjCa9a/gO6FRZlLA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dWFVVUlCTGZ0ZzNNZjBx
            bzU4K0ttbllORDQyQXJETHVLdnkrczFWMzJNCmhjQ0JkOGlKRmY5cjlTSnJjOWxa
            amVTb1VPN1QxcUJVc2IzSzZMcitBbHcKLS0tIGttc0FiRmRKVFpyVGhhZE52bzV0
            U3crWWh6b3V2Ly93bGhjaGhBV2NvUzQKJkB5jVo8iSVWjA/ZrqNI2zHGKYPVO/7d
            7S93SILyrgexsRBXW5hpQ4J/rnYRiwn1WhEe8Zk5GhwSGjM8DdPuOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pwt0aqwrfk98gcj9mtmdldrvg42a4aue24dlwyak6qrcdvjcd52qsejkvy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T08:00:35Z"
    mac: ENC[AES256_GCM,data:B/lW7ESGaQiVTPlSPM+fJIEb6qfpn2JltasHQhR1/m9/gakvAQOA62ciBFQbwmS2yGxdXyT+CDm5DTAZ05ZF7BtOBMWCxYhjGBvILN7ArWpdEvkbnSesCfjQgLZzpJalZEp6YUGKI93edVlwpwBvFjE3WBUBjdLUfbmzQFO3DoQ=,iv:3mwLDUhoQQAf+9w1dR9W5w6anZUt7QnypVFHW3h5yf0=,tag:yAALLTmaoFGKulYganV5Sg==,type:str]
    version: 3.13.3
