apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.36.1
          ports:
            - containerPort: 3005
          securityContext:
            allowPrivilegeEscalation: false
          envFrom:
            - configMapRef:
                name: audiobookshelf-configmap
          volumeMounts:
            - name: audiobookshelf-config
              mountPath: /config
            - name: audiobookshelf-metadata
              mountPath: /metadata
            - name: audiobookshelf-data-audiobooks
              mountPath: /audiobooks
            - name: audiobookshelf-data-podcasts
              mountPath: /podcasts
      volumes:
        - name: audiobookshelf-config
          persistentVolumeClaim:
            claimName: audiobookshelf-config-pvc
        - name: audiobookshelf-metadata
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata-pvc
        - name: audiobookshelf-data-audiobooks
          persistentVolumeClaim:
            claimName: audiobookshelf-data-audiobooks-pvc
        - name: audiobookshelf-data-podcasts
          persistentVolumeClaim:
            claimName: audiobookshelf-data-podcasts-pvc
