apiVersion: v1
data:
    password: ENC[AES256_GCM,data:0qiIkFyELdY=,iv:X/5BDyNEhGfS6beWg6HiHopMrpYd6Pvb/4c+nrCItFw=,tag:GFzO7B4owCKteF8BgqlQaw==,type:str]
    user: ENC[AES256_GCM,data:noKJvIOwl68=,iv:zxWGzEyy1ncY/+DEoyg6PALxozsxQGzGY9YqA/1Cr5o=,tag:wGJ4QnROrhgT4qPo7gEN7Q==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbEVSeElySmJtUk05aFpN
            ZWxMMFBGZEFtWVpuZ0NLOG9mdkNJUlE0TlZjCkdLQThUdG5ySHRhdFZiTDJWQWt1
            YnJ2Q1IwcjdNaXZYWUxxVCtaVE5KUmcKLS0tIHpzYlpjcUM0OHd2MDBEc3lERTd2
            U1VRR0NtTmVNVDFUb2YrMjJ5OFp2UVEKZ5FoDPcRwG4PIudWTE/muXtFEoJf3lJz
            +KbEbix8QfXSIcvMvHaSdfxzLxrBw5nNYhO2Y+t2HUmQFVB3ZQiM4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pwt0aqwrfk98gcj9mtmdldrvg42a4aue24dlwyak6qrcdvjcd52qsejkvy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T09:10:47Z"
    mac: ENC[AES256_GCM,data:7pM931/cuZNvt8K9dToyg5xegp4/9agqt61wAXJld73pV/7/shCHnQlHoB/hrnQBomzramwhwLWfgguR51bXXT1jwOM0imbhvuAQcIuMHiQ+STOhZgSpRTIa98p9Zt6Rl+UtvkwRjMNo3A6ksz6SHe2xNjyuBIaPoMKPc+zlN2g=,iv:V68Ww3NLLw8/nBU9terQh/VX7RfTupphW3yJB6nkuCk=,tag:/Yy/TXPshehcWOl5i/KCpA==,type:str]
    version: 3.13.3
