apiVersion: v1
data:
    8b623563-0ece-480f-8fd2-2529340b7491.json: ENC[AES256_GCM,data:Sgu7Cxq/+zN96wqcdFh5KoI17/qNEPbYPZyBFc6ssQwqbq49yIyj0dnRsvOlO/lMDR80tmTR6lf/k6FFKqtLUfoywZOUsm7V6XznWl3RMAwx892hQJVdjS/iHYTlbQ/1VzovvwhF9VTy2bPfpmBwhZ1448ieighWj5Nd4AeAHXxsazZJLUmCbCCiuPX00dAGgyS4r2MG1x22ulcdhgJORCwNKeC9TlE1jPWUxQU8UO0oWNvCaNzH2YODjKTSjzsYA2PVAkRvUltpLOYp1ZPcT9E+Ho1A98YftpqhJejNsX9LNkIORJ395CUdwSI=,iv:rYR9ishnCsVB75eB8bTaSNTM/vtWXWmvGCEQ5QmpRAE=,tag:z5FcCjqh1GLWa/eFRswFuw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVXgyeURjaUhRNVhqcnpW
            S0RpN2tSZjZ0NlVyandtejc1VkNUWjU5Wmk4ClZyTHpEYi9va2R4c3dndlJNSUxL
            NDVTNjJ6Q21LWWhTU3ROZnFBN0ZUZW8KLS0tIFJRRWxFNlR3d3RZVHh4cFV3U0hO
            eE9QdWVkM0dPL2VtMm5LaTBqUDU3ak0KRyQcfBuXthvisA1puMPr7Nn8InNd4P0e
            JgtWbnP3Gxb8YU7wl/9h64ndtRoe8OYIK2N9M0vz2WVGTNU/xyqNxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pwt0aqwrfk98gcj9mtmdldrvg42a4aue24dlwyak6qrcdvjcd52qsejkvy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T12:52:38Z"
    mac: ENC[AES256_GCM,data:6WFp1+InYd20SYFpGqMcKjo/NtzHBUZLrBGysuBoofILL44MXowwV8gSm4lNdpzGSoJXLwgSsS/ef3mxe5f6FQtlINBfJYnoNmE0XcTcMC9M+FYvf9mpx2E+7mbf4ZUG5pIOoPLoldQAjjhYMbmGG6ttXrpyba2RByBMJ3JfWzs=,iv:6dGKWys3Eri0hS99ScDGyHpw61YiVz1+d7xflODE5Rk=,tag:k/e4tGRxEel0e3MQw1Y5Uw==,type:str]
    version: 3.13.3
