apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:nifjQM/m1D5kjJKd+Lm0hZqufLVOvvAapmYwLtUbsHCS3uuZiDUy8jkdEyUlKkS6JHjGiOKWIvHcEQQk/yIqfVl8Bj0Ewq0SQVNe+8tK/FOJOzTTnqBdrp3Vq0MBqJxrdo81mzpfJcF8rchI/sdY7TEf/tCaV+cLwaFiNxtJS1bKcewOE4ksLMTu/1LKGVCraznH6u23RtWspiNg1NjyI6zLkNdFToo3YfZVOJ96VInkcvHoU9wqoS7pHw9AU8kewpcffjaWU/a5OeyZrY4SVWPLf10Q1yahTMpCdj7b0e6qZVX1SC00Fb+HuMw=,iv:QFteMfOsnoY7J+xTK2CXqEWlI1nC8ErKEb191y+0qKQ=,tag:JW34fAR0nST9eZvDDurICQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZk5KbFNpcUVxUDlWVXcz
            WGM1ZndDK0VwRXBIQXhPWElLR0s2Vy9tTVhVCloyTzIyRFFsQkVlcXJsRHI3MEly
            VFZVUWRldGpUZWZCTlpieGdBQjNTamMKLS0tIElzZlROd1l1Um9UdkNEWDQwdldV
            eDdrbzZvQlBoSGNjMlRNZnMrOGVIb1EKpI6mRJqeC6CxruADKII3GR0IFJf6ADu7
            nhZ+V+mFCCkq90kja3NDrzkhbL8UjBoAyIF5qztEcnVTefqjMyNIFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pwt0aqwrfk98gcj9mtmdldrvg42a4aue24dlwyak6qrcdvjcd52qsejkvy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T13:36:55Z"
    mac: ENC[AES256_GCM,data:jn/BBW6qwFBHNfhFNzQrkr9qPAco/eNnmAJKp2ceKfFaUJViVFkIg7miMzWBjBNFitcJ75cSL+TZhB/9tGYZA/Sa4Xbeff0fnMymNCi0BLOt7RvF0uYaan0XR/I4Tp5mn/4RGbJYvr4hXQCOUtVykBAysnvO/XW44AJj4/ndTl0=,iv:Hxtn8tzdW/s32pWWNl3qI3aYx7xJWKFAT3gypHMu/8I=,tag:PAbSIP2OmDoCCqJzlZqzmQ==,type:str]
    version: 3.13.3
