apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:2d1zK2Z3JNY=,iv:bK23uhhakXVUpJvk7N9GArpJ9j/otUbhTSWsd8rvSws=,tag:o5IKdkgAXVJjDuX5VTaaoA==,type:str]
    password: ENC[AES256_GCM,data:kI0hTh0PhzXrU6dc,iv:s+Kuce6oYdTs7AprbrAcuQIllMGv1HPs4Dq5aRyhipk=,tag:jvz8xJKGZOGBiCn/Dk2f7g==,type:str]
kind: Secret
metadata:
    name: linkding-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaWtISlNWcERaYnJOMkVJ
            QUJVNjVGSkE4MHB1UkZTM0hQUHNNZUVIRUhvCnhua25UbExOZ3BwcXRpV0Rrcmxa
            NGVkcHl6MkxHbXFnbmpTdFJsekhDZ1UKLS0tIDB3bXBrWXQ1ZTRBV3d2N1B6V2pS
            K1BISU1NWjY1TXJTbThjS2RZd0pQNFEKvg4i7KT6dHzh+hfV86mHRqxtliWqQBCX
            qSiu8XAU/M3Wy98H5r5Gkr5C0ZIDPITFCQI8aKhdplf1kIQc0cO8VQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pwt0aqwrfk98gcj9mtmdldrvg42a4aue24dlwyak6qrcdvjcd52qsejkvy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T13:14:44Z"
    mac: ENC[AES256_GCM,data:KoqofNNdHOabqFgiJNjOC+pWrrvcTqLys3qbLwpo/SpznXAVm6MPvQ0tBG+E+GeIIQJHxe4pZ6C/sNSEq91sRX8cn631fiQw2o9OwCKQBotmNs+yL/Ans56XR+lj4Z+dwek922LXKJs4Q8QhP+Rq0SacL41urcdjubU8ZB+8gVE=,iv:+iTVPFYQLjgtiY71jsIW0SRUD82qFljemRtvnIVOS+M=,tag:3r4NvyYVTXVlbOnLRRu4gA==,type:str]
    version: 3.13.3
